### PR TITLE
Append element on show instead of on init.

### PR DESCRIPTION
**Pull request by dfcreative**
Related to https://github.com/component/dialog/issues/21

### CODE REVIEW

**Comment by dfcreative** [comment]
@pirxpilot, @juliangruber, @rauchg  please merge)
If you grant access to this repo, I won’t bother you anymore, sorry )

**Comment by pirxpilot** [comment]
Doesn't it make things even worse? Won't we be adding overlay multiple times if someone calls `show` multiple times? I think it would better to fix `hide` in the way I described in component/dialog#21

**Comment by dfcreative** [comment]
An element can’t be added multiple times to the DOM. Just test in console:
```js
var d = document.createElement('div');
document.body.appendChild(d);
document.body.appendChild(d);
```
That is safe behavior.

For now if overlay was hidden, it is no more able to be shown once again. It is inconsistent behavior and factually hidden state.

I have a solution for dialog, but it needs the new version of the overlay-component first.

**Comment by pirxpilot** [comment]
Good point.

Still why not fix [`Dialog.hideOverlay`](https://github.com/component/dialog/blob/master/index.js#L264) - so that it does not reset `_overlay` property to null (which happens to be the root cause of component/dialog#21)

It seems less disruptive than changing this component.

**Comment by dfcreative** [comment]
I’ve made a PR to component-dialog https://github.com/component/dialog/pull/30.
It seems to be the solution you suggest

**Comment by pirxpilot** [comment]
You know what: you're right on this one. It only makes sense that we add element in `show` if we are removing it in `hide` - I was under impression we are just adding/removing the 'hidden' class.
I'll take it into master and release it, but please clean up the white spaces and push an update.

Also could you hold on for a moment on dialog changes. I'd like to have another look.

**Comment by dfcreative** [comment]
Right, whitespaces. Done.

**Comment by pirxpilot** [comment]
Thanks. 0.3.5 tagged.
Next time feel free to unleash your git squash superpowers ;-)

**Comment by dfcreative** [comment]
Got it, thanks)

**Pull request merged**
